#pragma once

#include <cule/config.hpp>

#include <cule/atari/games/detail/attributes.hpp>
#include <cule/atari/games/detail/types.hpp>
#include <cule/atari/games/detail/utils.hpp>

#include <cule/atari/games/adventure.hpp>
#include <cule/atari/games/airraid.hpp>
#include <cule/atari/games/alien.hpp>
#include <cule/atari/games/amidar.hpp>
#include <cule/atari/games/assault.hpp>
#include <cule/atari/games/asterix.hpp>
#include <cule/atari/games/asteroids.hpp>
#include <cule/atari/games/atlantis.hpp>
#include <cule/atari/games/bankheist.hpp>
#include <cule/atari/games/battlezone.hpp>
#include <cule/atari/games/beamrider.hpp>
#include <cule/atari/games/berzerk.hpp>
#include <cule/atari/games/bowling.hpp>
#include <cule/atari/games/boxing.hpp>
#include <cule/atari/games/breakout.hpp>
#include <cule/atari/games/carnival.hpp>
#include <cule/atari/games/centipede.hpp>
#include <cule/atari/games/chopper.hpp>
#include <cule/atari/games/crazyclimber.hpp>
#include <cule/atari/games/defender.hpp>
#include <cule/atari/games/demonattack.hpp>
#include <cule/atari/games/doubledunk.hpp>
#include <cule/atari/games/elevatoraction.hpp>
#include <cule/atari/games/enduro.hpp>
#include <cule/atari/games/fishingderby.hpp>
#include <cule/atari/games/freeway.hpp>
#include <cule/atari/games/frostbite.hpp>
#include <cule/atari/games/gopher.hpp>
#include <cule/atari/games/gravitar.hpp>
#include <cule/atari/games/hero.hpp>
#include <cule/atari/games/icehockey.hpp>
#include <cule/atari/games/jamesbond.hpp>
#include <cule/atari/games/journeyescape.hpp>
#include <cule/atari/games/kaboom.hpp>
#include <cule/atari/games/kangaroo.hpp>
#include <cule/atari/games/krull.hpp>
#include <cule/atari/games/kungfumaster.hpp>
#include <cule/atari/games/montezumarevenge.hpp>
#include <cule/atari/games/mspacman.hpp>
#include <cule/atari/games/namethisgame.hpp>
#include <cule/atari/games/phoenix.hpp>
#include <cule/atari/games/pinball.hpp>
#include <cule/atari/games/pitfall.hpp>
#include <cule/atari/games/pong.hpp>
#include <cule/atari/games/pooyan.hpp>
#include <cule/atari/games/privateeye.hpp>
#include <cule/atari/games/qbert.hpp>
#include <cule/atari/games/riverraid.hpp>
#include <cule/atari/games/roadrunner.hpp>
#include <cule/atari/games/robotank.hpp>
#include <cule/atari/games/seaquest.hpp>
#include <cule/atari/games/skiing.hpp>
#include <cule/atari/games/solaris.hpp>
#include <cule/atari/games/spaceinvaders.hpp>
#include <cule/atari/games/stargunner.hpp>
#include <cule/atari/games/tennis.hpp>
#include <cule/atari/games/timepilot.hpp>
#include <cule/atari/games/tutankham.hpp>
#include <cule/atari/games/upndown.hpp>
#include <cule/atari/games/venture.hpp>
#include <cule/atari/games/wizard.hpp>
#include <cule/atari/games/yarsrevenge.hpp>
#include <cule/atari/games/zaxxon.hpp>

